// Arabic translations for all UI text
export const AR = {
  // App
  appName: 'دنتافلو',
  appSub:  'نظام إدارة العيادة',
  clinicName: 'عيادة ابتسامة مشرقة',

  // Auth
  welcomeBack:     'أهلاً بعودتك',
  signIn:          'تسجيل الدخول',
  signingIn:       'جارٍ الدخول...',
  email:           'البريد الإلكتروني',
  password:        'كلمة المرور',
  forgotPassword:  'نسيت كلمة المرور؟',
  backToLogin:     'العودة لتسجيل الدخول',
  backToSite:      'العودة للموقع',
  sendCode:        'إرسال الكود',
  sending:         'جارٍ الإرسال...',
  checkEmail:      'تحقق من بريدك الإلكتروني',
  verifyCode:      'تحقق من الكود',
  verifying:       'جارٍ التحقق...',
  newPassword:     'كلمة المرور الجديدة',
  confirmPassword: 'تأكيد كلمة المرور',
  resetPassword:   'إعادة تعيين كلمة المرور',
  resetting:       'جارٍ الإعادة...',
  staffLogin:      'تسجيل دخول الموظفين',
  staffPortal:     'بوابة الموظفين',

  // Roles
  admin:        'مدير',
  doctor:       'طبيب',
  receptionist: 'موظف استقبال',

  // Sidebar nav
  overview:     'نظرة عامة',
  management:   'الإدارة',
  finance:      'المالية',
  account:      'الحساب',
  dashboard:    'لوحة التحكم',
  analytics:    'التحليلات',
  patients:     'المرضى',
  doctors:      'الأطباء',
  receptionists:'موظفو الاستقبال',
  payments:     'المدفوعات',
  debtAlerts:   'تنبيهات الديون',
  myProfile:    'ملفي الشخصي',
  myPatients:   'مرضاي',
  newPatient:   'مريض جديد',
  signOut:      'تسجيل الخروج',

  // Dashboard
  totalPatients:   'إجمالي المرضى',
  activeDoctors:   'الأطباء النشطون',
  totalCollected:  'إجمالي المحصّل',
  debtAlertCount:  'تنبيهات الديون',
  netProfit:       'صافي الربح المقدّر (60%)',
  grossRevenue:    'الإجمالي',
  clinicCosts:     'تكاليف العيادة (40%)',
  netProfitLabel:  'صافي الربح (60%)',
  basedOn:         'بناءً على',
  totalThisPeriod: 'إجمالي محصّل هذه الفترة',
  revenueOverview: 'نظرة على الإيرادات',
  monthlyIncome:   'الدخل الشهري',
  outstandingDebts:'الديون المتأخرة',
  outstandingBal:  'أرصدة متأخرة',
  recentPayments:  'آخر المدفوعات',
  recentPatients:  'آخر المرضى',
  allClear:        'كل شيء على ما يرام!',
  noOutstandingDebt:'لا توجد ديون متأخرة',
  noPaymentsYet:   'لا توجد مدفوعات بعد',
  noPatientsYet:   'لا يوجد مرضى بعد',
  noRevenueYet:    'لا توجد بيانات إيرادات بعد',
  refresh:         'تحديث',
  overview2:       'نظرة عامة',

  // Patient fields
  fullName:        'الاسم الكامل',
  age:             'العمر',
  phone:           'رقم الهاتف',
  gender:          'الجنس',
  male:            'ذكر',
  female:          'أنثى',
  address:         'العنوان',
  visitDate:       'تاريخ الزيارة',
  assignedDoctor:  'الطبيب المعالج',
  selectDoctor:    'اختر طبيباً...',
  paymentDetails:  'تفاصيل الدفع',
  totalCost:       'التكلفة الإجمالية (جنيه)',
  amountPaid:      'المبلغ المدفوع (جنيه)',
  remaining:       'المتبقي',
  remainingBalance:'الرصيد المتبقي',
  notes:           'ملاحظات',
  notesPlaceholder:'أي ملاحظات أولية...',
  status:          'الحالة',
  total:           'الإجمالي',
  paid:            'مدفوع',
  actions:         'الإجراءات',

  // Status
  active:    'نشط',
  pending:   'قيد الانتظار',
  completed: 'مكتمل',
  inactive:  'غير نشط',

  // Patient modals
  addNewPatient:    'إضافة مريض جديد',
  patientDetails:   'تفاصيل المريض',
  editPatient:      'تعديل بيانات المريض',
  diagnosis:        'التشخيص',
  treatment:        'خطة العلاج',
  payment:          'الدفع',
  updateDiagnosis:  'تحديث التشخيص',
  updateTreatment:  'تحديث خطة العلاج',
  updatePayment:    'تحديث الدفع',
  addPatient:       'إضافة المريض',
  adding:           'جارٍ الإضافة...',
  saveChanges:      'حفظ التغييرات',
  saving:           'جارٍ الحفظ...',
  cancel:           'إلغاء',
  close:            'إغلاق',
  edit:             'تعديل',
  delete:           'حذف',
  view:             'عرض',
  noPatients:       'لا يوجد مرضى',
  addFirst:         'أضف أول مريض للبدء',
  searchPatients:   'بحث بالاسم أو الهاتف...',
  paymentMethod:    'طريقة الدفع',
  selectMethod:     'اختر طريقة...',
  cash:             'نقداً',
  card:             'بطاقة',
  transfer:         'تحويل بنكي',
  insurance:        'تأمين',
  diagnosisDetails: 'أدخل تفاصيل التشخيص...',
  treatmentDetails: 'صف خطة العلاج...',
  noDiagnosis:      'لا يوجد تشخيص بعد',
  noTreatment:      'لا يوجد علاج بعد',
  fullyPaid:        '✓ مدفوع بالكامل',

  // Patient details page
  back:              'رجوع',
  backToPatients:    'رجوع لقائمة المرضى',
  patientInfo:       'بيانات المريض',
  financialStatus:   'الحالة المالية',
  totalCostLabel:    'إجمالي التكلفة',
  paidLabel:         'المدفوع',
  remainingLabel:    'المتبقي',
  paymentsCount:     'عدد الدفعات',
  lastPayment:       'آخر دفعة',
  firstVisit:        'تاريخ أول زيارة',
  lastVisit:         'تاريخ آخر زيارة',
  patientStatus:     'حالة المريض',
  assignedDoctorLbl: 'الطبيب المسؤول',
  appointmentsCard:  'المواعيد',
  viewAllAppointments:'عرض جميع المواعيد',
  noAppointments:    'لا توجد مواعيد بعد',
  imagesCard:        'الصور الطبية',
  addImage:          'إضافة صورة',
  viewImages:        'عرض الصور',
  noImages:          'لا توجد صور بعد',
  uploadingImage:    'جارٍ رفع الصورة...',
  deleteImage:       'حذف الصورة',
  followUpVisit:     'تسجيل متابعة',
  followUpVisitTitle:'تسجيل زيارة متابعة',
  visitCost:         'تكلفة الزيارة',
  amountPaidNow:     'المبلغ المدفوع',
  visitNotes:        'ملاحظات الزيارة',
  saveVisit:         'حفظ الزيارة',
  patientNotFound:   'تعذر العثور على بيانات المريض',
  loadingPatient:    'جارٍ تحميل بيانات المريض...',

  // Staff
  addDoctor:         'إضافة طبيب',
  addReceptionist:   'إضافة موظف استقبال',
  createDoctor:      'إنشاء حساب الطبيب',
  createReceptionist:'إنشاء حساب موظف الاستقبال',
  creating:          'جارٍ الإنشاء...',
  searchStaff:       'بحث...',
  name:              'الاسم',
  roleLabel:         'الدور',
  specialization:    'التخصص',
  selectSpec:        'اختر التخصص...',
  username:          'اسم المستخدم',
  roleSetDoctor:     'سيتم تعيين الدور: طبيب',
  roleSetReception:  'سيتم تعيين الدور: موظف استقبال',
  noStaffFound:      'لا يوجد موظفون',
  noData:            'لا توجد بيانات',

  // Specializations
  specs: ['طب الأسنان العام','تقويم الأسنان','علاج الجذور','أمراض اللثة','تركيبات الأسنان','جراحة الفم','طب أسنان الأطفال','تجميل الأسنان'],

  // Profile
  profileInfo:      'معلومات الملف الشخصي',
  personalInfo:     'المعلومات الشخصية',
  photos:           'الصور',
  security:         'الأمان',
  profilePicture:   'صورة الملف الشخصي',
  coverPhoto:       'صورة الغلاف',
  uploadPhoto:      'رفع صورة',
  changeCover:      'تغيير الغلاف',
  currentPassword:  'كلمة المرور الحالية',
  changePassword:   'تغيير كلمة المرور',
  updatePassword:   'تحديث كلمة المرور',
  updating:         'جارٍ التحديث...',
  roleManaged:      'يتم إدارة صلاحيات الدور بواسطة مدير النظام',
  yourRole:         'دورك:',
  emailNoChange:    '(لا يمكن تغييره)',
  tooShort:         'قصير جداً',
  medium:           'متوسط',
  strong:           'قوي',
  noMatch:          'كلمتا المرور غير متطابقتين',

  // Doctor dashboard
  goodDay:          'يوم سعيد،',
  practiceOverview: 'إليك نظرة عامة على عيادتك',
  activePatientsNow:'مريض نشط الآن',
  myPatients2:      'مرضاي',
  completedCases:   'الحالات المكتملة',
  pendingCases:     'الحالات المعلقة',
  patientActivity:  'نشاط المرضى',
  monthlyVisits:    'الزيارات الشهرية',
  noChartData:      'لا توجد بيانات بعد',
  collected:        'محصّل',

  // Receptionist dashboard
  welcomeBack2:     'أهلاً بعودتك،',
  pendingToday:     'حالة قيد الانتظار اليوم',
  allCaughtUp:      'كل شيء على ما يرام اليوم!',
  totalPatients2:   'إجمالي المرضى',
  pending2:         'قيد الانتظار',
  completed2:       'مكتمل',
  viewAll:          'عرض الكل',
  registerNew:      'تسجيل مريض جديد',
  viewAllPatients:  'عرض كل المرضى',
  browseManage:     'تصفح وإدارة المرضى',
  viewPayments:     'عرض سجلات الدفع',

  // Landing
  landingBadge:     'العيادة الأولى في القاهرة',
  landingTitle1:    'ابتسامتك',
  landingTitle2:    'تبدأ هنا',
  landingDesc:      'رعاية أسنان متقدمة بلمسة لطيفة. من التنظيف الروتيني إلى التجميل الكامل — نحن هنا في كل خطوة.',
  bookAppointment:  'احجز موعدك',
  ourServices:      'خدماتنا',
  scrollDown:       'اسحب للأسفل',
  whatsOffer:       'ما نقدمه',
  comprehensiveServices: 'خدمات أسنان شاملة',
  serviceDesc:      'من الوقاية إلى الكمال — كل خدمة تحتاجها تحت سقف واحد.',
  aboutUs:          'من نحن',
  aboutTitle:       'طب أسنان مدفوع بالرعاية والابتكار',
  aboutDesc1:       'في عيادة ابتسامة مشرقة، ندمج أحدث التقنيات مع رعاية حقيقية. فريقنا من المتخصصين ملتزم بتقديم نتائج استثنائية في بيئة مريحة وخالية من القلق.',
  aboutDesc2:       'سواء كانت زيارتك الأولى أو كنت مريضاً قديماً، نعامل كل ابتسامة كأنها ابتسامتنا.',
  patientStories:   'قصص المرضى',
  realSmiles:       'ابتسامات حقيقية، نتائج حقيقية',
  readySmile:       'هل أنت مستعد لابتسامة أجمل؟',
  bookNow:          'احجز موعداً الآن ←',
  callUs:           'اتصل بنا',
  emailUs:          'راسلنا',
  visitUs:          'زورنا',
  workingHours:     'مواعيد العمل',
  footerRights:     'جميع الحقوق محفوظة',
  yearsExp:         '+سنة خبرة',
  happyPatients:    '+مريض سعيد',
  expertDoctors:    'طبيب متخصص',
  satisfactionRate: 'معدل الرضا',
  isoCertified:     'معتمد ISO',
  painFree:         'علاج بلا ألم',
  sameDay:          'مواعيد في نفس اليوم',
}
